version: '3.3'
services:
  client0:
    environment:
      - GET_HOSTS_FROM=dns
    image: "imseg-client:latest"
    build:
      context: .
    working_dir: /app
    command: /venv/bin/fedn run client -in client.yaml
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./data/datapartitions/0:/app/data:ro #mount as READ ONLY
      - ./client.yaml:/app/client.yaml
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "imseg-client:latest"
    build:
      context: .
    working_dir: /app
    command: /venv/bin/fedn run client -in client.yaml
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:

      - ./data/datapartitions/1:/app/data:ro #mount as READ ONLY
      - ./client.yaml:/app/client.yaml